services:
  app:
    build:
      context: .
      target: final
    container_name: flask_app
    depends_on:
      - db
      - seed_runner
    networks:
      - front_net
      - back_net

  nginx:
    image: nginx:1.29.3-alpine
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - front_net

  db:
    image: postgres:18.1-alpine
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 2s

  migration_runner:
    build:
      context: .
      target: final
    container_name: migration_runner
    depends_on:
      db:
        condition: service_healthy
    networks:
      - back_net
    command: ["python", "migrations/migrate.py"]
    restart: "no"

  seed_runner:
    build:
      context: .
      target: final
    container_name: seed_runner
    depends_on:
      - migration_runner
    networks:
      - back_net
    volumes:
      - seed_output:/seed_output
    command: ["python", "seed/run_seed.py"]
    restart: "no"

networks:
  front_net:
  back_net:

volumes:
  db_data:
  nginx_logs:
  seed_output:
