name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build builder image
        run: docker build --target builder -t projekt-builder .

      - name: Run tests
        run: docker build --target test -t projekt-test .

      - name: Build final image
        run: docker build --target final -t projekt-final .

      - name: Log in to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push final image
        run: |
          docker tag projekt-final ghcr.io/${{ github.repository_owner }}/projekt-final 
          docker push ghcr.io/${{ github.repository_owner }}/projekt-final

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4.31.6
        with:
          languages: python

      - name: Perform CodeQL Scan
        uses: github/codeql-action/analyze@v4.31.6
